// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFOIR2YLwbCVQPvd-4Zt7UVuCy5G8ZnA',
    appId: '1:920782692727:android:7f12988f96e09708f7c172',
    messagingSenderId: '920782692727',
    projectId: 'project-manager-e05f1',
    storageBucket: 'project-manager-e05f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhc_zrhM9bZ3civBKuxHNFeamgm_P3eEs',
    appId: '1:920782692727:ios:f39bc4235d911daaf7c172',
    messagingSenderId: '920782692727',
    projectId: 'project-manager-e05f1',
    storageBucket: 'project-manager-e05f1.appspot.com',
    iosBundleId: 'com.gadsonmulonga.projectManaging',
  );
}
